# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0711b372de88ad5c4caab91277666cc11ec0115644a07e7d942c9b600b4e8d3d19cfa8b803fff3e3cef8a72926b4b34bf0be92e34862b3faf8c2c6760d2aa5

test:
  secret_key_base: 1db6a4db636a0bb92a53d71e1f6e9fa8fd5520f32671bd0489e8357753c9c476a3b41d05953bf3c9bf740b34485b42dacf509dd45b958a9570c9bcd315588a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
